### ISSUE TITLE
group___functions.html not found

### ISSUE THREAD

**Issue by CrimsonCube** [GHGibonus/Atom-boilua#4]
```
Traceback (most recent call last):
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\main.py", line 42, in <module>
    scrapAndSerialize(sys.argv[1], sys.argv[2])
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\main.py", line 36, in scrapAndSerialize
    api = AfterbirthApi(docPath)
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\scraper.py", line 415, in __init__
    self.namespaces = [LuaNamespace(f) for f in nsFiles + funFiles]
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\scraper.py", line 415, in <listcomp>
    self.namespaces = [LuaNamespace(f) for f in nsFiles + funFiles]
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\scraper.py", line 279, in __init__
    with open(namespacePath, 'r') as namespaceFile:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Steam\\steamapps\\common\\The Binding of Isaac Rebirth\\tools\\LuaDocs\\group___functions.html'
```

Seems to be the same as issue #3 but with `group___functions.html` which is now called `group__funcs.html`.

**Comment by CrimsonCube** [comment]
Merging pull #5 will fix the issue.
