### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by CrimsonCube** [GHGibonus/Atom-boilua#6]
```
Traceback (most recent call last):
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\main.py", line 42, in <module>
    scrapAndSerialize(sys.argv[1], sys.argv[2])
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\main.py", line 36, in scrapAndSerialize
    api = AfterbirthApi(docPath)
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\scraper.py", line 415, in __init__
    self.namespaces = [LuaNamespace(f) for f in nsFiles + funFiles]
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\scraper.py", line 415, in <listcomp>
    self.namespaces = [LuaNamespace(f) for f in nsFiles + funFiles]
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\scraper.py", line 287, in __init__
    raise e
  File "C:\Users\poiuy\.atom\packages\Atom-boilua\lib\scraper\scraper.py", line 282, in __init__
    self.name = RE_NAMESPACE_NAME.search(content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Happens when opening a file.

**Comment by CrimsonCube** [comment]
Oops, forgot to change one of the filenames from issue #4. Closing.
