### ISSUE TITLE
Uncaught TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by arthegon** [GHGibonus/Atom-boilua#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [Atom-boilua](https://github.com/GHGibonus/Atom-boilua) package 1.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'close' of undefined

```
At C:\Users\arthe\.atom\packages\Atom-boilua\lib\idelike\game_handler.coffee:58

TypeError: Cannot read property 'close' of undefined
    at GameHandler.module.exports.GameHandler.killReaders (/packages/atom-boilua/lib/idelike/game_handler.coffee:58:19)
    at GameHandler.killReaders (/packages/atom-boilua/lib/idelike/game_handler.coffee:1:1)
    at Object.module.exports.launch_isaac (/packages/atom-boilua/lib/main.coffee:198:26)
    at /packages/atom-boilua/lib/main.coffee:170:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.3/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:27.2.0 intentions:highlight (input.hidden-input)
     -2:27.1.0 core:copy (input.hidden-input)
     -2:24.7.0 intentions:highlight (input.hidden-input)
     -2:24.5.0 core:paste (input.hidden-input)
     -2:11.1.0 Atom-boilua:launch-game (input.hidden-input)
     -2:08.0 intentions:highlight (input.hidden-input)
     -2:07.9.0 core:save (input.hidden-input)
     -2:07.0 Atom-boilua:launch-game (input.hidden-input)
     -1:58.7.0 application:show-settings (atom-text-editor.editor.is-focused)
     -1:22.9.0 core:copy (input.hidden-input)
     -0:38.1.0 core:move-left (input.hidden-input)
 25x -0:37.7.0 core:move-right (input.hidden-input)
     -0:35.1.0 core:move-left (input.hidden-input)
 28x -0:34.7.0 core:backspace (input.hidden-input)
     -0:32.9.0 core:paste (input.hidden-input)
  2x -0:25.3.0 Atom-boilua:launch-game (input.hidden-input)
```

### Non-Core Packages

```
Atom-boilua 1.4.4 
autocomplete-lua 0.8.3 
busy-signal 1.4.3 
dash-syntax 0.3.0 
dash-ui 0.4.2 
file-icons 2.1.11 
french-menu 0.2.2 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-lua 1.0.4 
linter-pycodestyle 2.1.2 
linter-python-pep8 0.2.0 
linter-ui-default 1.6.7 
linter-xmllint 1.4.3 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-selection 4.5.0 
python-autopep8 0.1.3 
title-bar-replacer 1.3.0 
```

**Comment by GHGibonus** [comment]
Thank you for the error report. I'll be looking into what I can do when I have time. I'm currently in an exam session and I might be very busy for the following week.
